services:
    laravel.test:
        build:
            context: ./
            dockerfile: Dockerfile
        image: casi_peer_review_image
        container_name: casi_peer_review-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - "./:/var/www"
        networks:
            - casi_peer_review
        depends_on:
            - pgsql
    pgsql:
        image: "postgres:17"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "casi_peer_review-pgsql:/var/lib/postgresql/data"
        networks:
            - casi_peer_review
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
    nginx:
        image: nginx:alpine
        container_name: casi_peer_review-nginx
        restart: unless-stopped
        ports:
            - ${APP_PORT:-8080}:80
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d\
        networks:
            - casi_peer_review
    node:
        platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
        build:
            context: .
            dockerfile: Dockerfile.node
        image: casi_peer_review-node
        container_name: casi_peer_review-node
        ports:
            - "3000:3000"
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - /var/www/node_modules
        networks:
            - casi_peer_review
    composer:
        image: composer:latest
        user: "1000:1000"
        container_name: casi_peer_review-composer
        volumes:
            - ./src:/var/www/
        working_dir: /var/www/
        depends_on:
            - php
        networks:
            - casi_peer_review
    artisan:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: casi_peer_review-artisan
        volumes:
            - ./src:/var/www/html
        depends_on:
            - pgsql
        working_dir: /var/www/html
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - casi_peer_review
networks:
    casi_peer_review:
        driver: bridge
volumes:
    casi_peer_review-pgsql:
        driver: local
