services:
    laravel.test:
        build:
            args:
                user: user
                uid: 1000
        context: ./
        dockerfile: Dockerfile
        image: ${APP_NAME}
        container_name: casi_peer_review-app
        restart: unless-stopped
        working_dir: /var/www/
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${APP_PORT:-80}:8000"
            - "8000:80"
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        volumes:
            - "./:/var/www"
        networks:
            - casi_peer_review
        depends_on:
            - pgsql
    pgsql:
        image: "postgres:17"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "casi_peer_review-pgsql:/var/lib/postgresql/data"
        networks:
            - casi_peer_review
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
    nginx:
        image: nginx:alpine
        container_name: app_name-nginx
        restart: unless-stopped
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./nginx:/etc/nginx/conf.d\
        networks:
            - casi_peer_review
networks:
    casi_peer_review:
        driver: bridge
volumes:
    casi_peer_review-pgsql:
        driver: local
