services:
    app:
        build:
            context: "./vendor/laravel/sail/runtimes/8.4"
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: "sail-8.4/app"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "80:80"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        volumes:
            - ".:/var/www/html"
        networks:
            - sail
        depends_on:
            - pgsql
    pgsql:
        image: "postgres:17"
        restart: always
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
    ngrok:
        image: "ngrok/ngrok:alpine"
        environment:
            NGROK_AUTHTOKEN: "${NGROK_AUTHTOKEN}"
        command: "http laravel.test:8000"
        ports:
            - "4040:4040"
        networks:
            - sail
        depends_on:
            - laravel.test

networks:
    sail:
        driver: bridge
volumes:
    sail-pgsql:
        driver: local
