version: "3.8"

services:
    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "${APP_PORT:-80}:80" # Expose port 80 for the app
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app_network
        depends_on:
            - php
        restart: always

    # PHP-FPM Service
    php:
        build:
        context: .
        dockerfile: php.dockerfile
        ports:
            - "9000:9000"
        volumes:
            - ./src:/var/www/html:delegated
        networks:
            - laravel

    # PostgreSQL Service
    pgsql:
        image: "postgres:17"
        container_name: pgsql
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
        networks:
            - app_network
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
        restart: always

    composer:
        build:
        context: .
        dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html
        depends_on:
            - php
        entrypoint: ["composer", "--ignore-platform-reqs"]
        networks:
            - laravel

    npm:
        image: node:current-alpine
        volumes:
            - ./src:/var/www/html
        ports:
            - "3000:3000"
            - "3001:3001"
            - "5173:5173"
        working_dir: /var/www/html
        entrypoint: ["npm"]
        networks:
            - laravel

    artisan:
        build:
        context: .
        dockerfile: php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated
        depends_on:
            - pgsql
        entrypoint: ["php", "/var/www/html/artisan"]
        networks:
            - laravel

networks:
    app_network:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
