services:
    laravel.test:
        build:
            context: ./
            dockerfile: Dockerfile
        image: casi_peer_review_image
        container_name: casi_peer_review-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - "./:/var/www"
        networks:
            - casi_peer_review
        depends_on:
            - pgsql
    nginx:
        image: nginx:alpine
        container_name: casi_peer_review-nginx
        restart: unless-stopped
        ports:
            - ${APP_PORT:-80}:80
        volumes:
            - ./:/var/www/
            - ./nginx:/etc/nginx/conf.d/
        depends_on:
            - pgsql
        networks:
            - casi_peer_review
    pgsql:
        image: "postgres:17"
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "casi_peer_review-pgsql:/var/lib/postgresql/data"
        networks:
            - casi_peer_review
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
networks:
    casi_peer_review:
        driver: bridge
        external: true
volumes:
    casi_peer_review-pgsql:
        driver: local
