version: "3.8"

services:
    # Nginx Service
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "${APP_PORT:-80}:80" # Expose port 80 for the app
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app_network
        depends_on:
            - php
        restart: always

    # PHP-FPM Service
    php:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        container_name: php-fpm
        volumes:
            - .:/var/www/html
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
        networks:
            - app_network
        restart: always

    # PostgreSQL Service
    pgsql:
        image: "postgres:17"
        container_name: pgsql
        ports:
            - "${FORWARD_DB_PORT:-5432}:5432"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        volumes:
            - "sail-pgsql:/var/lib/postgresql/data"
        networks:
            - app_network
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s
        restart: always

networks:
    app_network:
        driver: bridge

volumes:
    sail-pgsql:
        driver: local
